# Generated by Django 3.1.1 on 2020-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20201006_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_field',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
